// <auto-generated />
using System;
using MCOP.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCOP.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20220216203239_StatsActive")]
    partial class StatsActive
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("xf")
                .HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("MCOP.Database.Models.BotStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Activity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activity_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("bot_statuses", "xf");
                });

            modelBuilder.Entity("MCOP.Database.Models.ImageHash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("GuildIdDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gid");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("hash");

                    b.Property<long>("MessageIdDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mid");

                    b.HasKey("Id");

                    b.HasIndex("GuildIdDb", "MessageIdDb");

                    b.ToTable("image_hashes", "xf");
                });

            modelBuilder.Entity("MCOP.Database.Models.PrivilegedUser", b =>
                {
                    b.Property<long>("UserIdDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.HasKey("UserIdDb");

                    b.ToTable("privileged_users", "xf");
                });

            modelBuilder.Entity("MCOP.Database.Models.UserMessage", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gid");

                    b.Property<long>("MessageIdDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mid");

                    b.HasKey("GuildIdDb", "MessageIdDb");

                    b.ToTable("user_messages", "xf");
                });

            modelBuilder.Entity("MCOP.Database.Models.UserStats", b =>
                {
                    b.Property<long>("GuildIdDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gid");

                    b.Property<long>("UserIdDb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uid");

                    b.Property<int>("DuelLose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("duel_lose");

                    b.Property<int>("DuelWin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("duel_win");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<int>("Like")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("like");

                    b.HasKey("GuildIdDb", "UserIdDb");

                    b.ToTable("user_stats", "xf");
                });

            modelBuilder.Entity("MCOP.Database.Models.ImageHash", b =>
                {
                    b.HasOne("MCOP.Database.Models.UserMessage", "Message")
                        .WithMany("Hashes")
                        .HasForeignKey("GuildIdDb", "MessageIdDb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MCOP.Database.Models.UserMessage", b =>
                {
                    b.Navigation("Hashes");
                });
#pragma warning restore 612, 618
        }
    }
}
