// <auto-generated />
using System;
using MCOP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCOP.Data.Migrations
{
    [DbContext(typeof(McopDbContext))]
    [Migration("20251110150537_GuildMessageCreateAt")]
    partial class GuildMessageCreateAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MCOP.Data.Models.ApiUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiUsages");
                });

            modelBuilder.Entity("MCOP.Data.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordRefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscordTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("MCOP.Data.Models.BotStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Activity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BotStatuses");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LevelUpMessageTemplate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LevelUpMessagesEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("LewdChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LikeEmojiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LikeEmojiName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LogChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReactionTrackingEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessage", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("GuildMessages");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessageReaction", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HistoricalIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("EmojiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "MessageId", "CreatedByUserId", "HistoricalIndex", "EmojiId", "Emoji");

                    b.ToTable("GuildMessageReactions");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildRole", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGainExpBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelToGetRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LevelUpMessageTemplate")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("GuildRoles");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildUserStats", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuelLose")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuelWin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastExpAwardedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("GuildUserStats");
                });

            modelBuilder.Entity("MCOP.Data.Models.ImageHash", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "MessageId");

                    b.ToTable("ImageHashes");
                });

            modelBuilder.Entity("MCOP.Data.Models.ImageVerificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImageVerificationChannels");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessageReaction", b =>
                {
                    b.HasOne("MCOP.Data.Models.GuildMessage", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("GuildId", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MCOP.Data.Models.ImageHash", b =>
                {
                    b.HasOne("MCOP.Data.Models.GuildMessage", "GuildMessage")
                        .WithMany("ImageHashes")
                        .HasForeignKey("GuildId", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMessage");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessage", b =>
                {
                    b.Navigation("ImageHashes");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
