// <auto-generated />
using System;
using MCOP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCOP.Data.Migrations
{
    [DbContext(typeof(McopDbContext))]
    [Migration("20250306050632_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MCOP.Data.Models.BotStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Activity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BotStatuses");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("LewdChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("LogChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessage", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("GuildMessages");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildUserEmoji", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("EmojiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecievedAmount")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "UserId", "EmojiId");

                    b.ToTable("GuildUserEmojies");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildUserStats", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuelLose")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuelWin")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastExpAwardedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("GuildUserStats");
                });

            modelBuilder.Entity("MCOP.Data.Models.ImageHash", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "MessageId");

                    b.ToTable("ImageHashes");
                });

            modelBuilder.Entity("MCOP.Data.Models.ImageHash", b =>
                {
                    b.HasOne("MCOP.Data.Models.GuildMessage", "GuildMessage")
                        .WithMany("ImageHashes")
                        .HasForeignKey("GuildId", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMessage");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessage", b =>
                {
                    b.Navigation("ImageHashes");
                });
#pragma warning restore 612, 618
        }
    }
}
