// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MCOP.Data;

namespace MCOP.Data.Migrations
{
    [DbContext(typeof(McopDbContext))]
    [Migration("20260407191740_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MCOP.Data.Models.ApiUsage", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiUsages");
                });

            modelBuilder.Entity("MCOP.Data.Models.AppUser", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("MCOP.Data.Models.BotStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BotStatuses");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildConfig", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("BlockedRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ExpMessageChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LevelUpMessageChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LikeEmojiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LikeEmojiName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LevelUpMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LevelUpMessagesEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReactionTrackingEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessage", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("GuildMessages");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessageReaction", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HistoricalIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("EmojiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "MessageId", "CreatedByUserId", "HistoricalIndex", "EmojiId", "Emoji");

                    b.ToTable("GuildMessageReactions");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildRole", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuildRoles");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildUserStats", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuelWin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuelLose")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastExpAwardedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("GuildUserStats");
                });

            modelBuilder.Entity("MCOP.Data.Models.ImageHash", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImageHashes");
                });

            modelBuilder.Entity("MCOP.Data.Models.ImageVerificationChannel", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImageVerificationChannels");
                });

            modelBuilder.Entity("MCOP.Data.GuildUserStatsProjection", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuelWin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuelLose")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessageReaction", b =>
                {
                    b.HasOne("MCOP.Data.Models.GuildMessage", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("GuildId", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
