// <auto-generated />
using System;
using MCOP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MCOP.Data.Migrations
{
    [DbContext(typeof(McopDbContext))]
    [Migration("20260801143441_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MCOP.Data.GuildUserStatsProjection", b =>
                {
                    b.Property<string>("AvatarHash")
                        .HasColumnType("text");

                    b.Property<int>("DuelLose")
                        .HasColumnType("integer");

                    b.Property<int>("DuelWin")
                        .HasColumnType("integer");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("MCOP.Data.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DiscordAccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiscordRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscordTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("MCOP.Data.Models.BotStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Activity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("BotStatuses");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("LevelUpMessageTemplate")
                        .HasColumnType("text");

                    b.Property<bool>("LevelUpMessagesEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LewdChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("LikeEmojiId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("LikeEmojiName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("LogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("ReactionTrackingEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessage", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("GuildMessages");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessageReaction", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("CreatedByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("HistoricalIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("EmojiId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Emoji")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "MessageId", "CreatedByUserId", "HistoricalIndex", "EmojiId", "Emoji");

                    b.ToTable("GuildMessageReactions");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildRole", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsGainExpBlocked")
                        .HasColumnType("boolean");

                    b.Property<int?>("LevelToGetRole")
                        .HasColumnType("integer");

                    b.Property<string>("LevelUpMessageTemplate")
                        .HasColumnType("text");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("GuildRoles");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildUserStats", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("text");

                    b.Property<int>("DuelLose")
                        .HasColumnType("integer");

                    b.Property<int>("DuelWin")
                        .HasColumnType("integer");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastExpAwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("GuildUserStats");
                });

            modelBuilder.Entity("MCOP.Data.Models.ImageHash", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "MessageId");

                    b.ToTable("ImageHashes");
                });

            modelBuilder.Entity("MCOP.Data.Models.ImageVerificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("ImageVerificationChannels");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessageReaction", b =>
                {
                    b.HasOne("MCOP.Data.Models.GuildMessage", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("GuildId", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MCOP.Data.Models.ImageHash", b =>
                {
                    b.HasOne("MCOP.Data.Models.GuildMessage", "GuildMessage")
                        .WithMany("ImageHashes")
                        .HasForeignKey("GuildId", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMessage");
                });

            modelBuilder.Entity("MCOP.Data.Models.GuildMessage", b =>
                {
                    b.Navigation("ImageHashes");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
